name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 14 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-web-cypress-report
          path: cypress/reports/

      - name: Download test report
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: test-web-cypress-report
          path: cypress/reports/
      
      - name: Summary report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Summary report
          path: "cypress/reports/junit/results-*.xml"
          reporter: jest-junit
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
          