name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 14 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g npm

      - name: Run Cypress tests with tag
        run: npx cypress run --env TAGS=@search

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-web-cypress-report
          path: cypress/reports/

      - name: Download test report
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: test-web-cypress-report
          path: cypress/reports/
      
      - name: Summary report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Summary report
          path: "cypress/reports/junit/results-*.xml"
          reporter: jest-junit
          